/**
 * @file ePICAssociationsManager.h
 * @brief Handles unpacking of PODIO One-To-Many relationships dynamically using a Fluent Builder API.
 * @details
 * This manager decouples the low-level detector hit/cluster association logic from the core physics kinematics 
 * inside `ePICReaction`. It uses a **Fluent Builder Pattern** (method chaining) to provide an intuitive interface 
 * for mapping nested PODIO arrays into flat, padded `RDataFrame` columns.
 * * The manager completely shields the user from complex JIT string manipulations and ensures the resulting 
 * arrays are perfectly synchronized with the unified `rec_det_id` track arrays generated by the `ParticleInjector`.
 * * **Fluent API Code Structure & Example:**
 * The `For()` method initializes a transient `ColumnBuilder` object. Methods like `From()`, `Extract()`, and 
 * `Relation()` return a reference to this builder, allowing them to be chained together sequentially. 
 * The `As()` method acts as the terminal operation, finalizing the configuration and registering the variable.
 * Finally, `Build()` constructs the unified padded arrays.
 * * \code
 * epic::ePICAssociationManager assoc(rad_df);
 * * // Define cluster energy extraction for the Central tracker
 * assoc.For("Central")
 * .Relation("clusters") // (Optional) defaults to "clusters"
 * .From({"EcalBarrelClusters", "EcalEndcapPClusters", "EcalEndcapNClusters"})
 * .Extract("energy")
 * .Reduce("rad::util::First") // (Optional) defaults to First
 * .As("cal_energy", "double"); // Automatically maps to padded "rec_cal_energy"
 * * // Execute JIT compilation to pad arrays using rec_det_id
 * assoc.Build(); 
 * \endcode
 */

#pragma once

#include <string>
#include <vector>
#include <unordered_map>
#include <stdexcept>
#include <ROOT/RVec.hxx>
#include "PodioAssociation.h"
#include "StringUtilities.h"
#include "Constants.h" 
#include "DefineNames.h" 

namespace rad {
namespace epic {

    class ePICReaction; 

    /**
     * @struct AuxVar
     * @brief Stores metadata for a generated auxiliary column to facilitate array padding.
     */
    struct AuxVar {
        std::string type;                                            ///< The C++ type (e.g. "double")
        std::string name;                                            ///< Unique name of the auxiliary variable
        std::string defaultVal;                                      ///< Default value for padding (usually NaN)
        std::unordered_map<std::string, std::string> detectorCols;   ///< Maps a detector name to its raw projection column
    };

    /**
     * @class ePICAssociationManager
     * @brief Manages the registration and building of PODIO associations.
     */
    class ePICAssociationManager {
    public:
        class ColumnBuilder; 

        /**
         * @brief Constructor.
         * @param reaction Reference to the base ePICReaction managing the dataframe.
         */
        explicit ePICAssociationManager(ePICReaction& reaction);

        /**
         * @brief Initiates the Fluent Builder for a specific detector.
         * @param detName The name of the registered detector (e.g., "Central", "RP").
         * @return A transient ColumnBuilder object to chain commands.
         */
        ColumnBuilder For(const std::string& detName);

        /**
         * @brief Compiles all registered associations into unified, padded RDataFrame columns.
         * @details Must be called after all `For()...As()` chains, but before `MakeCombinations()`.
         */
        void Build();
        
        /** @return Constant reference to the registered auxiliary variables. */
        const std::vector<AuxVar>& GetAuxVars() const;

        /** @return Reference to the underlying reaction object. */
        ePICReaction& GetReaction() const;

        /**
         * @brief Defines the base PODIO associations using generalized branch names.
         * @details Constructs the One-To-Many nested arrays using `rad::podio::CreateAssociation`.
         * @param uniqueId The custom variable name (e.g. "cal_energy") to prevent clashes.
         * @param relationName The exact EDM4hep relation name (e.g. "clusters", "tracks").
         * @param collectionNames Valid PODIO hit collections to merge.
         * @param memberName The leaf member to extract.
         * @param baseBranch The primary tracker branch (e.g. "ReconstructedParticles").
         */
        void DefineInternal(const std::string& uniqueId, const std::string& relationName, 
                            const ROOT::RVec<std::string>& collectionNames, 
                            const std::string& memberName, const std::string& baseBranch);
                            
        /**
         * @brief Projects a nested One-To-Many association array into a flat scalar array.
         * @param outName Base name of the output column.
         * @param inputAssociation Name of the nested column to project.
         * @param funcName The reducer function (e.g., "rad::util::First").
         * @param detName The mapped detector name.
         * @param type The underlying data type.
         * @param defaultVal Default value string for missing data.
         */
        void Project(const std::string& outName, const std::string& inputAssociation, const std::string& funcName,
                     const std::string& detName, const std::string& type = "double", std::string defaultVal = "");
                     
        /**
         * @brief Registers an auxiliary variable into the internal padding map.
         * @param type Data type.
         * @param name Name of the final column.
         * @param defaultVal Value used to pad indices that lack associated data.
         * @param detName Name of the specific detector.
         * @param rawCol The name of the raw unpadded RDataFrame column.
         */
        void RegisterAuxiliary(const std::string& type, const std::string& name, const std::string& defaultVal,
                               const std::string& detName, const std::string& rawCol);

    private:
        ePICReaction& _reaction;      ///< Reference to the parent reaction managing the RDF node
        std::vector<AuxVar> _auxVars; ///< Registry of requested auxiliary columns
    };

    /**
     * @class ePICAssociationManager::ColumnBuilder
     * @brief Transient helper class that implements the Fluent API for column definition.
     */
    class ePICAssociationManager::ColumnBuilder {
    public:
        /**
         * @brief Constructor.
         * @param manager Reference to the parent manager.
         * @param detName The detector being mapped.
         */
        ColumnBuilder(ePICAssociationManager& manager, const std::string& detName);

        /**
         * @brief Sets the PODIO collections to extract data from.
         * @param cols List of valid EDM4hep collections.
         * @return Reference to the builder for chaining.
         */
        ColumnBuilder& From(const ROOT::RVec<std::string>& cols);

        /**
         * @brief Sets the specific leaf variable to extract from the collection.
         * @param member Member name (e.g., "energy", "time").
         * @return Reference to the builder for chaining.
         */
        ColumnBuilder& Extract(const std::string& member);

        /**
         * @brief Sets the reducer function used to collapse One-To-Many relations into scalars.
         * @param reducer Function name (e.g., "rad::util::Sum"). Defaults to First.
         * @return Reference to the builder for chaining.
         */
        ColumnBuilder& Reduce(const std::string& reducer);
        
        /**
         * @brief Explicitly set the EDM4hep Relation branch to read from.
         * @param rel The relation name (Defaults to "clusters", but could be "tracks").
         * @return Reference to the builder for chaining.
         */
        ColumnBuilder& Relation(const std::string& rel);

        /**
         * @brief Terminal operation. Finalizes the configuration and triggers the definitions.
         * @param outName The final desired name of the column (without type prefix).
         * @param type The underlying data type (default "double").
         * @param defaultVal Default padding value. If empty, uses `rad::consts::InvalidEntry`.
         */
        void As(const std::string& outName, const std::string& type = "double", std::string defaultVal = "");

    private:
        ePICAssociationManager& _manager; ///< Parent manager execution hook
        std::string _detName;             ///< Target detector string
        ROOT::RVec<std::string> _collections; ///< Target PODIO collections
        std::string _memberName;          ///< Leaf member
        std::string _reducerFunc;         ///< Reducer function
        std::string _relationName;        ///< EDM4hep Relation name
    };

} // namespace epic
} // namespace rad

// =================================================================================
// IMPLEMENTATION
// =================================================================================

#include "ePICReaction.h" 

namespace rad {
namespace epic {

    inline ePICAssociationManager::ePICAssociationManager(ePICReaction& reaction) : _reaction(reaction) {}

    inline ePICAssociationManager::ColumnBuilder ePICAssociationManager::For(const std::string& detName) {
        return ColumnBuilder(*this, detName);
    }

    inline const std::vector<AuxVar>& ePICAssociationManager::GetAuxVars() const { return _auxVars; }
    inline ePICReaction& ePICAssociationManager::GetReaction() const { return _reaction; }

    inline void ePICAssociationManager::RegisterAuxiliary(const std::string& type, const std::string& name, const std::string& defaultVal,
                                                          const std::string& detName, const std::string& rawCol) 
    {
        for (auto& aux : _auxVars) {
            if (aux.name == name) {
                if (!rawCol.empty()) aux.detectorCols[detName] = rawCol;
                return;
            }
        }
        AuxVar newAux{type, name, defaultVal, {}};
        if (!rawCol.empty()) newAux.detectorCols[detName] = rawCol;
        _auxVars.push_back(newAux);
    }

    inline void ePICAssociationManager::DefineInternal(const std::string& uniqueId, 
                                                       const std::string& relationName,
                                                       const ROOT::RVec<std::string>& collectionNames, 
                                                       const std::string& memberName,
                                                       const std::string& baseBranch) 
    {
        if(!_reaction.GetMetadata()) throw std::runtime_error("ePICAssociationManager::DefineInternal requires PodioMetadata.");
        if (collectionNames.empty()) return;

        ROOT::RVec<std::string> validNames;
        ROOT::RVecU validIDs;
        for(const auto& name : collectionNames) {
            if(_reaction.GetMetadata()->Exists(name)) {
                validNames.push_back(name);
                validIDs.push_back(_reaction.GetMetadata()->CollectionIDFor(name));
            }
        }
        if(validNames.empty()){
            throw std::runtime_error("ePICAssociationManager::DefineInternal input data does not have branch");
        }

        std::string recType = rad::consts::data_type::Rec();
        std::string dnwTag = rad::DoNotWriteTag();

        // 1. Unified Index
        std::string unifiedIdxName = recType + uniqueId + "_unified_idx" + dnwTag;
        if(!_reaction.ColumnExists(unifiedIdxName)) {
            rad::podio::IdToLocalIndexMap mapper(validIDs);
            _reaction.Define(unifiedIdxName, [mapper](const ROOT::RVecU& ids){ return mapper(ids); }, 
                             {"_" + baseBranch + "_" + relationName + ".collectionID"});
        }

        // 2. Prepare Inputs
        ROOT::RVec<std::string> leafCols;
        for(const auto& name : validNames) leafCols.push_back(name + "." + memberName);

        std::string typeName = _reaction.GetElementTypeName(leafCols[0]); 
        
        std::string packName = recType + uniqueId + "_" + memberName + "_pack" + dnwTag;
        _reaction.Define(packName, "ROOT::RVec<ROOT::RVec<" + typeName + ">>{" + rad::util::combineVectorToString(leafCols) + "}");

        // 3. Define Final Output
        std::string outputCol = recType + uniqueId + "_assoc" + dnwTag; 
        
        std::string assocExpr = "rad::podio::CreateAssociation<" + typeName + ">(" + 
            packName + ", " + 
            unifiedIdxName + ", " + 
            "_" + baseBranch + "_" + relationName + ".index, " +
            baseBranch + "." + relationName + "_begin, " +
            baseBranch + "." + relationName + "_end)";
                                
        _reaction.Define(outputCol, assocExpr);
    }

    inline void ePICAssociationManager::Project(const std::string& outName, 
                                                const std::string& inputAssociation, 
                                                const std::string& funcName,
                                                const std::string& detName,
                                                const std::string& type,
                                                std::string defaultVal) 
    {
        if (defaultVal.empty()) {
            defaultVal = "rad::consts::InvalidEntry<" + type + ">()";
        }

        std::string recType = rad::consts::data_type::Rec();
        std::string dnwTag = rad::DoNotWriteTag();

        std::string rawCol = (!detName.empty()) ? (recType + outName + "_raw" + dnwTag) : outName;
        auto inputString = inputAssociation + dnwTag;
        
        std::string expr = "ROOT::RVec<" + type + "> result; result.reserve(" + inputString + ".size()); "
                           "for(const auto& v : " + inputString + ") { "
                           "result.push_back(static_cast<" + type + ">(" + funcName + "(v))); } "
                           "return result;";
                           
        _reaction.Define(rawCol, expr);

        if (!detName.empty()) {
            RegisterAuxiliary(type, outName, defaultVal, detName, rawCol);
        }
    }

    // --- ColumnBuilder Implementations ---

    inline ePICAssociationManager::ColumnBuilder::ColumnBuilder(ePICAssociationManager& manager, const std::string& detName) 
        : _manager(manager), _detName(detName), _reducerFunc("rad::util::First"), _relationName("clusters") {} 

    inline ePICAssociationManager::ColumnBuilder& ePICAssociationManager::ColumnBuilder::From(const ROOT::RVec<std::string>& cols) {
        _collections = cols; return *this;
    }

    inline ePICAssociationManager::ColumnBuilder& ePICAssociationManager::ColumnBuilder::Extract(const std::string& member) {
        _memberName = member; return *this;
    }

    inline ePICAssociationManager::ColumnBuilder& ePICAssociationManager::ColumnBuilder::Reduce(const std::string& reducer) {
        _reducerFunc = reducer; return *this;
    }

    inline ePICAssociationManager::ColumnBuilder& ePICAssociationManager::ColumnBuilder::Relation(const std::string& rel) {
        _relationName = rel; return *this;
    }

    inline void ePICAssociationManager::ColumnBuilder::As(const std::string& outName, const std::string& type, std::string defaultVal) {
        if (defaultVal.empty()) {
            defaultVal = "rad::consts::InvalidEntry<" + type + ">()";
        }

        auto detDef = _manager.GetReaction().GetDetector(_detName);
        
        // Pass the unique name (outName) AND the PODIO relationship (_relationName)
        _manager.DefineInternal(outName, _relationName, _collections, _memberName, detDef.branch);
        
        std::string recType = rad::consts::data_type::Rec();
        
        // Project the newly created unique association column
        _manager.Project(outName, recType + outName + "_assoc", _reducerFunc, _detName, type, defaultVal);
    }

    inline void ePICAssociationManager::Build() {
        std::string recType = rad::consts::data_type::Rec();
        std::string detIdCol = recType + "det_id"; // Synced with ParticleInjector

        for (const auto& aux : _auxVars) {
            std::string finalCol = recType + aux.name; 
            
            std::string expr = "ROOT::RVec<" + aux.type + "> unified(" + detIdCol + ".size(), " + aux.defaultVal + "); ";
            
            // 1. Declare all local index trackers BEFORE the loop
            for (const auto& [detName, rawCol] : aux.detectorCols) {
                expr += "int local_idx_" + detName + " = 0; ";
            }
            
            // 2. Open the single loop
            expr += "for(size_t i = 0; i < " + detIdCol + ".size(); ++i) { ";
            
            // 3. Add an IF block for each detector inside the loop
            for (const auto& [detName, rawCol] : aux.detectorCols) {
                auto detDef = _reaction.GetDetector(detName);
                expr += "    if(" + detIdCol + "[i] == " + std::to_string(detDef.id) + ") { ";
                expr += "        if(local_idx_" + detName + " < " + rawCol + ".size()) { ";
                expr += "            unified[i] = " + rawCol + "[local_idx_" + detName + "]; ";
                expr += "        } ";
                expr += "        local_idx_" + detName + "++; ";
                expr += "    } ";
            }
            
            // 4. Close the loop and return
            expr += "} return unified;";

            _reaction.Define(finalCol, expr);
        }
    }
  
} // namespace epic
} // namespace rad
